# Generated by Django 5.2.3 on 2025-06-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="comleted",
            new_name="completed",
        ),
    ]
